In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [2]:
df=pd.read_csv('covid_toy.csv')

In [3]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [6]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever.shape

(80, 1)

In [15]:
X_train_fever

array([[ 98.        ],
       [ 99.        ],
       [ 99.        ],
       [104.        ],
       [104.        ],
       [104.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [101.        ],
       [100.60273973],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [101.        ],
       [ 99.        ],
       [ 98.        ],
       [100.60273973],
       [ 98.        ],
       [ 98.        ],
       [103.        ],
       [104.        ],
       [100.        ],
       [102.        ],
       [100.        ],
       [102.        ],
       [100.        ],
       [100.60273973],
       [102.        ],
       [ 98.        ],
       [ 99.        ],
       [104.        ],
       [101.        ],
       [101.        ],
       [100.        ],
       [102.        ],
       [104.        ],
       [104.        ],
       [ 99.        ],
       [101.        ],
       [ 99.        ],
       [ 98

In [7]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [16]:
X_train_cough

array([[0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],

In [31]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'


     ---------------------------------------- 0.0/8.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/8.9 MB 330.3 kB/s eta 0:00:27
     ---------------------------------------- 0.0/8.9 MB 330.3 kB/s eta 0:00:27
     ---------------------------------------- 0.0/8.9 MB 330.3 kB/s eta 0:00:27
     ---------------------------------------- 0.0/8.9 MB 178.6 kB/s eta 0:00:50
     ---------------------------------------- 0.1/8.9 MB 201.8 kB/s eta 0:00:44
     ---------------------------------------- 0.1/8.9 MB 231.0 kB/s eta 0:00:39
      --------------------------------------- 0.2/8.9 MB 459.5 kB/s eta 0:00:20
      --------------------------------------- 0.2/8.9 MB 409.6 kB/s eta 0:00:22
      --------------------------------------- 0.2/8.9 MB 504.4 kB/s eta 0:00:18
     - -------------------------------------- 0.2/8.9 MB 519.9 kB/s eta 0:00:17
     - -------------------------------------- 0.3/8.9 MB 553.0 kB/s eta 0:00:16
     - -------------------------------------- 0.

  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [641 lines of output]
  C:\Users\user\AppData\Local\Temp\pip-install-4gvhyahm\scikit-learn_19d5bf4499004a3e9d0fd4585e174eaa\setup.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import parse_version
  Partial import of sklearn during the build process.
  C:\Users\user\AppData\Local\Temp\pip-install-4gvhyahm\scikit-learn_19d5bf4499004a3e9d0fd4585e174eaa\setup.py:277: DeprecationWarning:
  
    `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
    of the deprecation of `distutils` itself. It will be removed for
    Python >= 3.12. For older Python versions it will remain present.
    It is recommended to use `setuptools < 60.0` for those Python versions.
    For more details, see:
      https://numpy.org/devdocs/reference/distutils_status_migration.html
  
  


In [26]:
X_train_gender_city

<80x4 sparse matrix of type '<class 'numpy.float64'>'
	with 88 stored elements in Compressed Sparse Row format>

In [19]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [21]:
X_train_age

array([[83],
       [65],
       [49],
       [51],
       [ 6],
       [34],
       [65],
       [18],
       [14],
       [64],
       [82],
       [15],
       [81],
       [38],
       [16],
       [31],
       [42],
       [14],
       [73],
       [23],
       [34],
       [65],
       [60],
       [16],
       [19],
       [74],
       [27],
       [33],
       [11],
       [38],
       [82],
       [64],
       [65],
       [25],
       [47],
       [81],
       [47],
       [64],
       [75],
       [51],
       [25],
       [19],
       [22],
       [69],
       [40],
       [56],
       [80],
       [24],
       [19],
       [12],
       [11],
       [17],
       [71],
       [68],
       [60],
       [51],
       [ 5],
       [69],
       [79],
       [42],
       [10],
       [75],
       [24],
       [72],
       [ 5],
       [55],
       [49],
       [10],
       [27],
       [26],
       [20],
       [20],
       [66],
       [82],
       [ 8],
       [71],
       [80],

In [20]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 2 has 0 dimension(s)

In [11]:
from sklearn.compose import ColumnTransformer

In [12]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

In [13]:
transformer.fit_transform(X_train).shape

NameError: name 'transformer' is not defined

In [14]:
transformer.transform(X_test).shape

NameError: name 'transformer' is not defined